# Generated by Django 6.1.1 on 2026-09-14 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0001_product_codesubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_url', models.URLField()),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('cloning', 'Cloning'), ('ready', 'Ready'), ('failed', 'Failed')], default='cloning', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_jobs', to='api_gateway.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
